# ================ JOIN MESSAGES ================

chat.connection.default.join=&2&l[&a&l+&2&l] &a{0} &2joined.
chat.connection.default.leave=&4&l[&c&l-&4&l] &c{0} &4left.

chat.connection.mr_cool.join=&2&l[&a&l+&2&l] &a{0} &2is in the building!
chat.connection.mr_cool.leave=&4&l[&c&l-&4&l] &c{0} &4out.

chat.connection.shakespeare.join=&2&l[&a&l+&2&l] &a{0} &2hath arrived.
chat.connection.shakespeare.leave=&4&l[&c&l-&4&l] &c{0} &4hath abandoned thee.

chat.connection.superhero.join=&2&l[&a&l+&2&l] &2Have no fear, &a{0} &2is here!
chat.connection.superhero.leave=&4&l[&c&l-&4&l] &c{0}&4's work here is done.

chat.connection.aviation.join=&2&l[&a&l+&2&l] &2It's a bird! It's a plane! It's &a{0}&2...
chat.connection.aviation.leave=&4&l[&c&l-&4&l] &c{0} &4flew off into the sunset.

chat.connection.monarch.join=&2&l[&a&l+&2&l] &2Bow down, for &a{0} &2has arrived.
chat.connection.monarch.leave=&4&l[&c&l-&4&l] &c{0} &4is gone. Weep in their absence.

chat.connection.reversed.join=&2&l[&a&l+&2&l] &a{0} &2left.
chat.connection.reversed.leave=&4&l[&c&l-&4&l] &c{0} &4joined.

chat.connection.stinky.join=&2&l[&a&l+&2&l] &2Smell that? It's &a{0}&2.
chat.connection.stinky.leave=&4&l[&c&l-&4&l] &4It's time for &c{0} &4to take a shower.