# ================ ANNOUNCEMENTS ================

chat.announcement.0=&8[&4Scoville&8] &7Have a player to report? Message online staff with &c/helpop&7!
chat.announcement.1=&8[&4Scoville&8] &7Want to get info, updates, and help on the server? Join our &cDiscord&7! &cdiscord.gg/qnG8qa4utm
chat.announcement.2=&8[&4Scoville&8] &7Make sure to read the &c/rules&7!
chat.announcement.3=&8[&4Scoville&8] &7Want to submit a &ccourse&7? Do so in &c#course-submission &7in our &cDiscord&7! &cdiscord.gg/qnG8qa4utm
chat.announcement.4=&8[&4Scoville&8] &7Want to change a setting? Click the &cOptions &7head!
chat.announcement.5=&8[&4Scoville&8] &7Use &c/prac &7to practice a jump!
chat.announcement.6=&8[&4Scoville&8] &7Level rewards can be viewed in the menu by clicking the &cexperience bottle&7!
chat.announcement.7=&8[&4Scoville&8] &7Beating a course gives a slight chance at obtaining a &cshiny tag&7!
chat.announcement.8=&8[&4Scoville&8] &cRedstone lamps &7teleport you back to your &ccheckpoint&7!
chat.announcement.9=&8[&4Scoville&8] &7There are &csecrets &7throughout the server. Can you find them all?
chat.announcement.10=&8[&4Scoville&8] &7We have &cachievements&7! View them in the &cmenu&7!

# ================ JOIN MESSAGES ================

chat.connection.default.join=&2&l[&a&l+&2&l] &a{0} &2joined.
chat.connection.default.leave=&4&l[&c&l-&4&l] &c{0} &4left.

chat.connection.mr_cool.join=&2&l[&a&l+&2&l] &a{0} &2is in the building!
chat.connection.mr_cool.leave=&4&l[&c&l-&4&l] &c{0} &4out.

chat.connection.shakespeare.join=&2&l[&a&l+&2&l] &a{0} &2hath arrived.
chat.connection.shakespeare.leave=&4&l[&c&l-&4&l] &c{0} &4hath abandoned thee.

chat.connection.superhero.join=&2&l[&a&l+&2&l] &2Have no fear, &a{0} &2is here!
chat.connection.superhero.leave=&4&l[&c&l-&4&l] &c{0}&4's work here is done.

chat.connection.aviation.join=&2&l[&a&l+&2&l] &2It's a bird! It's a plane! It's &a{0}&2...
chat.connection.aviation.leave=&4&l[&c&l-&4&l] &c{0} &4flew off into the sunset.

chat.connection.monarch.join=&2&l[&a&l+&2&l] &2Bow down, for &a{0} &2has arrived.
chat.connection.monarch.leave=&4&l[&c&l-&4&l] &c{0} &4is gone. Weep in their absence.

chat.connection.reversed.join=&2&l[&a&l+&2&l] &a{0} &2left.
chat.connection.reversed.leave=&4&l[&c&l-&4&l] &c{0} &4joined.

chat.connection.stinky.join=&2&l[&a&l+&2&l] &2Smell that? It's &a{0}&2.
chat.connection.stinky.leave=&4&l[&c&l-&4&l] &4It's time for &c{0} &4to take a shower.

# ================ HOTBAR ITEMS ================

item.hotbar.checkpoint.title=Checkpoint
item.hotbar.menu.title=Menu
item.hotbar.options.title=Options
item.hotbar.shield.title=Shield

# ================ TAG STUFF ================

tag.rank.owner.desc=&7Be the &f&lOwner&7!
tag.rank.admin.desc=&7Be an &c&lAdministrator&7!
tag.rank.mod.desc=&7Be a &e&lModerator&7!
tag.rank.helper.desc=&7Be a &a&lHelper&7!
tag.rank.builder.desc=&7Be a &7&lBuilder&7!
tag.rank.beta.desc=&7Be a &7&lBeta Tester&7!
tag.rank.buffoon.desc=&7Purchase the &c&lBuffoon &7rank!
tag.rank.moron.desc=&7Purchase the &e&lMoron &7rank!
tag.rank.idiot.desc=&7Purchase the &a&lIdiot &7rank!

tag.special.???.desc=&7???
tag.special.stone.desc=&7Complete all the courses that were found in &7&lSeason 1&7!
tag.special.grass.desc=&7Complete all the courses that were found in &a&lSeason 2&7!
tag.special.dirt.desc=&7Complete all the courses that were found in &6&lSeason 3&7!
tag.special.cobble.desc=&7Complete all the courses that were found in &7&lSeason 4&7!
tag.special.wood.desc=&7Complete all the courses that were found in &6&lSeason 5&7!
tag.special.sapling.desc=&7Complete all the courses that were found in &a&lSeason 6&7!
tag.special.bedrock.desc=&7Complete all the courses that were found in &8&lSeason 7&7!
tag.special.water.desc=&7Complete all the courses that were found in &9&lSeason 8&7!

tag.course.desc=&7Completed {0}&7!

tag.shiny.desc=&7Get lucky when beating {0}&7!

tag.record.desc=&7Be #1 on either {0} &7leaderboard!