smile=&e☺
frown=&9☹
heart=&c❤
gg=&2&lG&a&lG&f&l!
rip=&8&lR&7&lI&f&lP
win=&a&lWIN &2&l✔
fail=&c&lFAIL &4&l✘
tableflip=&e(╯&f°&e□&f°&e)╯&7︵&6┻━┻
shrug=&e¯\_(ツ)_/¯
pog=&cヽ&6(&e°&a〇&b°&d)&5ﾉ
owo=&e⁕&6✭&e⁕ &d\(&e☆&dω&e☆&d)/ &e⁕&6✭&e⁕